name: trad

packages:
  - ./**

scripts:
  analyze:
    help: Run the Dart linter on all source files.
    run: melos analyze --fatal-infos

  build.linux:
    help: Does a Linux build in release mode.
    steps:
      - cd main && flutter build linux --release
      - mkdir -p artifacts
      - cd main/build/linux/x64/release/bundle/ && zip -r trad_linux.zip .
      - mv main/build/linux/x64/release/bundle/trad_linux.zip artifacts/
      
  build.android:
    help: Does an Android build in release mode.
    steps:
      - cd main && flutter build apk --release
      - mkdir -p artifacts
      - mv main/build/app/outputs/flutter-apk/app-release.apk artifacts/trad_android.apk

  clean:
    help: Deletes local files that are generated during by melos tasks, e.g. build files and coverage information.
    steps:
      - find . -name dlcov_references_test.dart -exec rm {} \;
      - rm -rf ./coverage
      - melos exec rm -rf coverage
      - melos exec rm -rf build
      - rm -rf artifacts

  coverage:
    help: Calculates test coverage for the whole mobile application. 'melos run test' must have been executed before.
    steps:
      - find . -name lcov.info -exec rm {} \;
      - rm -rf ./coverage/report
      - melos exec --dir-exists=coverage/test dart run coverage:format_coverage --packages=.dart_tool/package_config.json --in=./coverage --out=./coverage/lcov.info --lcov --report-on=.
      - melos exec --dir-exists=coverage/test lcov --remove ./coverage/lcov.info \'*/dlcov_references_test.dart\' -o ./coverage/lcov.info
      - mkdir -p coverage
      - melos exec --dir-exists=coverage 'cat coverage/lcov.info >> ../coverage/lcov.info'
      - dart run cobertura convert
      - genhtml -o ./coverage/report ./coverage/lcov.info
      
  deploy.android:
    help: Install the build APK on the connected Android device (via ADB).
    run: adb install artifacts/*.apk

  format:
    help: Auto-format all source files according to our formatting rules.
    exec: dart format --line-length=100 --set-exit-if-changed .

  test:
    help: Run all unit tests for the mobile application.
    steps:
      - melos exec --dir-exists=test dart run dlcov gen-refs
      - melos exec --no-flutter --dir-exists=test dart test --coverage=./coverage
      - melos exec --flutter --dir-exists=test flutter test --coverage

  upgrade:
    help: Upgrades all dependencies to their most current (allowed) versions.
    steps:
      - melos exec rm -f pubspec_overrides.yaml
      - melos exec rm -f pubspec.lock
      - rm pubspec.lock
      - melos bootstrap
