name: trad

packages:
  - ./**

scripts:
  analyze:
    help: Run the Dart linter on all source files.
    run: melos analyze

  build.linux:
    help: Does a Linux build in release mode.
    steps:
      - cd main && flutter build linux --release
      - mkdir -p artifacts
      - mv main/build/linux/x64/release/bundle/main artifacts/
      
  build.android:
    help: Does an Android build in release mode.
    steps:
      - cd main && flutter build apk --release
      - mkdir -p artifacts
      - mv main/build/app/outputs/flutter-apk/app-release.apk artifacts/

  deploy.android:
    help: Install the build APK on the connected Android device (via ADB).
    run: adb install artifacts/*.apk

  format:
    help: Auto-format all source files according to our formatting rules.
    exec: dart format --line-length=100 --set-exit-if-changed .

  test:
    help: Run all unit tests for the mobile application.
    steps:
      - melos exec --no-flutter --dir-exists=test dart test
      - melos exec --flutter --dir-exists=test flutter test
